%kezi_stat;

figure;
hold on;
scatter(cat,stat.mini(:,1)+45,'o','filled');
scatter(cat,stat.maxi(:,1)+45,'o','filled');
grid on
grid minor

ref = zeros(1,27) + 45;
ylimhigh = zeros(1,27) + 63.4;
ylimlow = zeros(1,27) + 26.6;
ywarh = zeros(1,27) + 60;
ywarl = zeros(1,27) + 30;

plot(cat,ref,...
         '--',...
         'LineWidth',1,...
         'Color','black');
plot(cat,ylimlow,...
         '--',...
         'LineWidth',1,...
         'Color','red');
plot(cat,ylimhigh,...
         '--',...
         'LineWidth',1,...
         'Color','red');
plot(cat,ywarh,...
         '--',...
         'LineWidth',1,...
         'Color','#EDB120');
plot(cat,ywarl,...
         '--',...
         'LineWidth',1,...
         'Color','#EDB120');
     
legend("Minimum","Maximum","Model","NOK limit","NOK limit","Warning","Warning");